# coding: utf-8

from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    url(
        '^$',
        views.CompanyList.as_view(),
        name='crm-company-list',
    ),
    url(
        'archives/$',
        views.CompanyArchives.as_view(),
        name='crm-company-archives',
    ),
    url(
        '^cancel_assign/$',
        views.CancelAssign.as_view(),
        name='crm-cancel-assign',
    ),
    url(
        '^assign_admin/$',
        views.AssignAdmin.as_view(),
        name='crm-company-assign',
    ),
    url(
        '^contact/(?P<buy_resume_id>\d+)/$',
        views.ContactDownload.as_view(),
        name='crm-company-contact',
    ),
    url(
        '^detail/(?P<uid>\d+)/$',
        views.CompanyDetail.as_view(),
        name='crm-company-detail',
    ),
    url(
        '^download/(?P<uid>\d+)/$',
        views.CompanyDownload.as_view(
            need_contact=True,
        ),
        name='crm-company-download',
    ),
    url(
        '^overview/(?P<uid>\d+)/$',
        views.CompanyDownload.as_view(
            template_name='company/overview_list.html',
            paginate_by=20,
        ),
        name='crm-company-overview',
    ),
    url(
        '^offer/(?P<uid>\d+)/$',
        views.CompanyDownload.as_view(
            template_name='company/overview_list.html',
            paginate_by=20,
        ),
        name='crm-company-offer',
    ),
    url(
        '^entry/(?P<uid>\d+)/$',
        views.CompanyDownload.as_view(
            template_name='company/overview_list.html',
            paginate_by=20,
        ),
        name='crm-company-entry',
    ),
    url(
        '^eliminate/(?P<uid>\d+)/$',
        views.CompanyDownload.as_view(
            need_contact=True,
            template_name='company/overview_list.html',
            paginate_by=20,
        ),
        name='crm-company-eliminate',
    ),
    url(
        '^contacted/(?P<uid>\d+)/$',
        views.CompanyDownload.as_view(
            template_name='company/overview_list.html',
            paginate_by=20,
        ),
        name='crm-company-contacted',
    ),
    url(
        '^invite_interview/(?P<uid>\d+)/$',
        views.CompanyDownload.as_view(
            template_name='company/overview_list.html',
            paginate_by=20,
        ),
        name='crm-company-invite-interview',
    ),
    url(
        '^job/(?P<uid>\d+)/$',
        views.CompanyJob.as_view(
            all_job=False,
        ),
        name='crm-company-job',
    ),
    url(
        '^job_option/(?P<uid>\d+)/$',
        views.CompanyJob.as_view(
            template_name='company/job_option.html',
            all_job=False,
        ),
        name='crm-job-select',
    ),
    url(
        '^export/(?P<uid>\d+)/$',
        views.CompanyDownloadCSVExport.as_view(),
        name='crm-export-current-company',
    ),
    url(
        '^export_all/(?P<uid>\d+)/$',
        views.CompanyDownloadCSVExport.as_view(
            export_type='export_all_company',
        ),
        name='crm-csv-all-export',
    ),
)
